<a href="https://colab.research.google.com/github/safaltasaxena/deep-learning-mini-projects/blob/main/WordEmbeddingSup/Word_Embedding_SupVis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install tensorflow

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
reviews=['nice food',
         'amazing resturant',
         'too good',
         'just loved it',
         'will go again',
         'horrible food',
         'never go there',
         'poor service',
         'poor quality',
         'needs improvement']
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])


In [ ]:
one_hot("amazing resturant",30)
#giving random nos to all

[20, 8]

In [ ]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)


[[8, 2], [20, 8], [7, 11], [15, 15, 10], [3, 28, 13], [13, 2], [22, 28, 9], [23, 27], [23, 5], [15, 20]]


In [ ]:
max_length=3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[ 8  2  0]
 [20  8  0]
 [ 7 11  0]
 [15 15 10]
 [ 3 28 13]
 [13  2  0]
 [22 28  9]
 [23 27  0]
 [23  5  0]
 [15 20  0]]


In [ ]:
from tensorflow.keras.layers import Input

model = Sequential([
    Input(shape=(max_length,)),
    Embedding(input_dim=vocab_size, output_dim=embeded_vector_size,name='embeddings'),
    Flatten(),
    Dense(1, activation='sigmoid')
])

In [ ]:
X=padded_reviews
y=sentiment

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embeddings (Embedding)          │ (None, 3, 5)           │           150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_6 (Flatten)             │ (None, 15)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │            16 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 166 (664.00 B)

 Trainable params: 166 (664.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=50,verbose=0)

In [ ]:
loss,accuracy=model.evaluate(X,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - accuracy: 1.0000 - loss: 0.6323


1.0

In [ ]:
weights = model.get_layer('embeddings').get_weights()[0]

In [ ]:
len(weights)

30

In [ ]:
weights[8]

array([ 0.00928893, -0.07392309, -0.09686998,  0.00456002,  0.00677859],
      dtype=float32)

In [ ]:
weights[20]

array([-0.06564786,  0.04129318,  0.0129366 , -0.04438101, -0.03377359],
      dtype=float32)